### ISSUE TITLE
gh actions generates merge conflicts via depends.Rds

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [nmfs-fish-tools/nmfspalette#14]
Hi,

The automated actions to style the code (I think) keep generating merge conflicts in the `.github/r-depends.Rds` file which seems to be just a big table of hexadecimal numbers. Do you know what could be going on here?

**Comment by Bai-Li-NOAA** [comment]
Thanks for posting the issues. I updated the .github/.gitignore and added .rds to the file. Also, I deleted r-depends.rds to resolve the issue.
