### ISSUE TITLE
add a link to NOAA Fisheries branding source materials

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-fish-tools/nmfspalette#18]
I see the materials for the Fisheries Brand Guide on Google Drive at https://drive.google.com/drive/folders/1fy1pAwo9F6GW0asyxdNPFD4YhXT_PUng with the direct link to the PDF explainer document at https://drive.google.com/drive/folders/1MPFBbkYAn_HcZlVmZWxfYbLsKJ8sVVjw.
I'm not finding any public source of those June 2019 materials on the web.

I think that background information is useful to know how the color palettes were intended to be used (whether we adhere to those intentions or not).

**Comment by ChristineStawitz-NOAA** [comment]
added a link to the README, thanks @iantaylor-NOAA
