### ISSUE TITLE
Not enough contrast

### ISSUE THREAD

**Issue by okenk** [nmfs-fish-tools/nmfspalette#19]
I tried to use these palettes for a presentation, but found that the sequential palettes (the first six) did not provide much contrast from low to high values so were a bit ineffective, and I opted for a different palette. There may be more use of these palettes if there is a greater visual difference in the hues.

**Comment by BenWilliams-NOAA** [comment]
I'll 2nd what @okenk said

**Comment by ChristineStawitz-NOAA** [comment]
I will pass this along to the comms team that created the colors! I don't think they provide a high-contrast option other than the regional web one, unfortunately, and I don't control over the color scheme.

**Comment by ChristineStawitz-NOAA** [comment]
I just went back to the branding guidance, and they did update it in 2022! I will replace with these colors but I could use feedback on if this fixes the contrast issue.
