### ISSUE TITLE
github.io link not working

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/nmfspalette#5]
this link was also not working: https://nmfs-general-modeling-tools.github.io/nmfspalette/

**Comment by Bai-Li-NOAA** [comment]
The repo was moved from nmfs-general-modeling-tools organization to nmfs-fish-tools organization so the link was not working?

Other repos that use the extra.css from the nmfspalette may need to update their pkgdown extra.css file using the code below?
```css
@import url("https://nmfs-fish-tools.github.io/nmfspalette/extra.css");
```

**Comment by k-doering-NOAA** [comment]
That was exactly the issue @Bai-Li-NOAA ! https://nmfs-fish-tools.github.io/nmfspalette/ works (just changing the org)

**Comment by Bai-Li-NOAA** [comment]
Thanks Kathryn. 

@ChristineStawitz-NOAA and @HaleyOleynik-NOAA, could you change the url under the `About` section? I realized that I do not have access to change that link. I will use GitHub REST API to see if I can retrieve data and find out who are using pkgdown.

**Comment by ChristineStawitz-NOAA** [comment]
Done - thank you!
